baseURL = "https://serene-bell-2f6d05.netlify.com/"
languageCode = "en-us"
title = "LPFA"

[frontmatter]
  date  = [":filename", ":default"]

[permalinks]
  news = ":year/:month/:day/:slug"

[taxonomies]
  category = "categories"
  type = "types"
  tag = "tags"
  destination = "destination"  

Paginate = 5

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5