baseURL = "https://lesterpickerphoto.com/"
languageCode = "en-us"
title = "LPFA"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      xhtml = false

[frontmatter]
  date  = [":filename", ":default"]

[permalinks]
  news = ":year/:month/:day/:slug"

[outputFormats.Algolia]
  baseName = "algolia"
  isPlainText = true
  mediaType = "application/json"
  notAlternative = true

[params.algolia]
  vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
  params = ["categories", "tags"]

[outputs]
  home = ["HTML", "RSS", "Algolia"]

[taxonomies]
  category = "categories"
  type = "types"
  tag = "tags"
  destination = "destination"  

Paginate = 5

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
